<?php
/*CLASES*/
require_once("classes/class-checkout.php");
require_once("classes/class-paquete.php");
require_once("classes/class-pago-facil.php");
require_once("classes/class-pago-conekta.php");
require_once("classes/class-instructor.php");
require_once("classes/class-ubicacion.php");
require_once("classes/class-salon.php");
require_once("classes/class-clase.php");
require_once("classes/class-calendario.php");
require_once("classes/class-reserva.php");
require_once("classes/class-pedido.php");
require_once("classes/class-logo_prensa.php");
require_once("classes/class-entrada.php");
require_once("classes/class-cupon.php");
require_once("classes/class-cliente.php");
require_once("classes/class-producto.php");
/*MAILINGS*/
require_once("mailings/cargar_mailings.php");

?>
